name: Weekly stats

on:
  schedule:
    - cron: "1 9 * * 1"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}

    steps:
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Install os dependencies
        run: sudo apt update && sudo apt install curl jq git

      - name: Create stats file
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/sp1thas/dropboxignore/master/src/utils/stats.sh)" '${{ secrets.GITHUB_TOKEN }}'
